import Vue from 'vue'
import {
    Button,
    Form,
    FormItem,
    Input,
    Container,
    Header,
    Aside,
    Main,
    Row,
    Col,
    RadioGroup,
    Menu,
    RadioButton,
    Submenu,
    MenuItemGroup,
    MenuItem,
    Breadcrumb,
    BreadcrumbItem,
    Card,
    Table,
    TableColumn,
    Switch,
    Pagination

}
    from
    'element-ui'
Vue.use(Pagination)
Vue.use(Switch)
Vue.use(Card)
Vue.use(TableColumn)
Vue.use(Table)
Vue.use(BreadcrumbItem)
Vue.use(Breadcrumb)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(RadioButton)
Vue.use(Submenu)
Vue.use(RadioGroup)
Vue.use(Menu)
Vue.use(Col)
Vue.use(Row)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)